### ISSUE TITLE
Eager loading sopport?

### ISSUE THREAD

**Issue by zzantares** [Osedea/laravel-rest#2]
Hello, thanks for this amazing library it reduces much of the work with controllers, I like it, however reading the instructions I don't see how is possible to use [eager loading](http://laravel.com/docs/5.1/eloquent-relationships#eager-loading), is there a way to make it work?

For example if I have order and payment models, I don't want the payments to be queried directly (thus `api/v1/payments` not exists), but if an order is queried (`api/v1/orders/1`) then I want to return its related payments as well. How this can be done?

Thanks!

**Comment by adamburvill** [comment]
Hi @ZzAntares,

From the readme:

```
Nesting
Use this only when you REALLY need to.
If you absolutely need nested relations, you specify them like so:
/users?embed=groups
```

So you should be able to do 
`/orders?embed=payments`

**Comment by zzantares** [comment]
Wow thanks for you fast response, works great, thank you! but what I need to do in order to keep the same uri? I mean, I want the output of `api/v1/orders/1?embed=payments` but keeping the uri `api/v1/orders/1` however when querying all orders `api/v1/orders`  I don't want to show the payments.

Thanks in advance.

**Comment by Mopolo** [comment]
Hey @ZzAntares,

There's currently no way to achieve what you want. You need to specify `/orders/1?embed=payments` every time.
