### ISSUE TITLE
Apply middleware/filters to routes?

### ISSUE THREAD

**Issue by zzantares** [Osedea/laravel-rest#4]
Hello, it's me again, this time I need to add the `oauth` middleware to all routes generated buy this package, how can I achieve such thing?

I could add support for that, but may be is already possible, so I need to ask.

Thanks.

**Comment by cmburcus** [comment]
hi, given that this package is a bit old and the team that was maintaining it is no longer doing so, do you still need assistance with this issue? (i recon it is very old and you probably fixed what you needed by now)

**Comment by zzantares** [comment]
Haha in deed this is an old issue, no worries I noticed this repo was abandoned years ago. In the end I just forked and added what I needed, but as of today I'm not even using it. In fact there's still a PR open that I did at the time, I'll close the issue, since there's nothing I need anymore, thanks for answering though.
